#include "StdAfx.h"
#include "Resource.h"

WISP_TOOLBAR_RES_ITEM MainToolbar[]=
{
	{EVENT_ID_LOAD_MODULE,66,WISP_TBIS_BUTTON,WSTR("File -> Load module for debugging"),0,WISP_WS_DISABLED},
	{EVENT_ID_LOAD_EXPORT_SYMBOLS,22,WISP_TBIS_BUTTON,WSTR("File -> Load Module Export Symbols"),0,WISP_WS_DISABLED},
	{EVENT_ID_LOAD_SYMBOL_SYSERAPP,10,WISP_TBIS_BUTTON,WSTR("File -> Load symbol file"),0,WISP_WS_DISABLED},
	{EVENT_ID_TRANSLATE_SYMBOL,50,WISP_TBIS_BUTTON,WSTR("File -> Translate symbol file"),0},
	WISP_TOOLBAR_RES_SEPARATOR,
	{EVENT_ID_START_SYSER,	62,	WISP_TBIS_BUTTON,WSTR("File -> Start Syser"),	0},
	{EVENT_ID_STOP_SYSER,	31,	WISP_TBIS_BUTTON,WSTR("File -> Stop Syser"),	0,WISP_WS_DISABLED},
	WISP_TOOLBAR_RES_SEPARATOR,
	{EVENT_ID_SEND_CLIPBOARD,20,WISP_TBIS_BUTTON,WSTR("View -> Send Clipboard to Syser Debugger")},
	{EVENT_ID_RECV_CLIPBOARD,21,WISP_TBIS_BUTTON,WSTR("View -> Receive Clipboard from Syser Debugger")},
	WISP_TOOLBAR_RES_SEPARATOR,
	{EVENT_ID_DEBUG_MESSAGE_FILTER,57,WISP_TBIS_BUTTON,WSTR("View -> Debug Message Filter"),0},
	{EVENT_ID_DEBUG_MESSAGE_CLEAR,9,WISP_TBIS_BUTTON,WSTR("View -> Clear Console&Debug Message"),0},
	WISP_TOOLBAR_RES_END
};

WISP_MENU_RES_ITEM RecentFileMenu[]=
{
	{WSTR("Empty"),EVENT_ID_RECENT_FILE_SYSERAPP,132},
	WISP_MENU_RES_END
};

WISP_MENU_RES_ITEM LoaderMenu[]=
{
	{WSTR("Load For Debugging"),		EVENT_ID_LOAD_MODULE,66,WISP_MIS_DISABLED},
	{WSTR("Recent Files"),0,36,WISP_MIS_POPUP,RecentFileMenu},
	WISP_MENU_RES_SEPARATOR,
	{WSTR("Load Export Symbols"),		EVENT_ID_LOAD_EXPORT_SYMBOLS,22,WISP_MIS_DISABLED},
	{WSTR("Load Module's SDS"),					EVENT_ID_LOAD_SYMBOL_SYSERAPP,10,WISP_MIS_DISABLED},
	{WSTR("Load IDA map file"),			EVENT_ID_LOAD_IDA_MAP,10},	
	{WSTR("Translate Debugging Data To SDS"),	EVENT_ID_TRANSLATE_SYMBOL,50},		
	WISP_MENU_RES_SEPARATOR,
	{WSTR("Export Command Histroy"),	EVENT_ID_SAVE_HISTROYS,63},
	WISP_MENU_RES_SEPARATOR,
	{WSTR("Exit"),EVENT_ID_EXIT,132},
	WISP_MENU_RES_END
};

WISP_MENU_RES_ITEM KernelDebuggerMenu[]=
{
	{WSTR("Start Syser"),					EVENT_ID_START_SYSER,62},
	{WSTR("Stop Syser"),					EVENT_ID_STOP_SYSER,31,WISP_MIS_DISABLED},
	WISP_MENU_RES_SEPARATOR,
	{WSTR("Send Clipboard to Syser"),		EVENT_ID_SEND_CLIPBOARD,20},
	{WSTR("Receive Clipboard from Syser"),	EVENT_ID_RECV_CLIPBOARD,21},
	WISP_MENU_RES_SEPARATOR,
	{WSTR("Save Syser Comments"),			EVENT_ID_SAVE_COMMENTS,9*16+3,WISP_MIS_DISABLED},
	{WSTR("Export Command Histroy"),		EVENT_ID_SAVE_SYSER_HISTROYS,63,WISP_MIS_DISABLED},
	WISP_MENU_RES_END
};


WISP_MENU_RES_ITEM ViewMenu[]=
{
	{WSTR("Pause|Resume Debug Message"),EVENT_ID_DEBUG_MESSAGE,0,WISP_MIS_CHECKBOX|WISP_MIS_CHECKED},
	{WSTR("Debug Message Filter"),EVENT_ID_DEBUG_MESSAGE_FILTER,57},
	{WSTR("Clear Console&Debug Message"),EVENT_ID_DEBUG_MESSAGE_CLEAR,9},
	WISP_MENU_RES_END
};

WISP_MENU_RES_ITEM HelpMenu[]=
{
	{WSTR("Check New Version"),	EVENT_ID_CHECKNEWVERSION,	104},
#ifndef __DEMO__VERSION__
	{WSTR("Enter Register Key"),EVENT_ID_REGISTER,			81},
#endif
	{WSTR("Command Reference"),	EVENT_ID_COMMAND_REFERENCE,	30},
	{WSTR("Debug Help"),		EVENT_ID_DEBUG_HELP,		30},
	{WSTR("About Syser"),		EVENT_ID_ABOUT_SYSERAPP,				62},
	WISP_MENU_RES_END
};

WISP_MENU_RES_ITEM ToolsMenu[]=
{
	{WSTR("Option"),EVENT_ID_OPTION,83},
	{WSTR("Boot Option"),EVENT_ID_BOOT_OPTION,16*14+4},
	{WSTR("Video Option"),EVENT_ID_VIDEO_DETECT_MODE,19},
	WISP_MENU_RES_SEPARATOR,
	{WSTR("Symbol Downloader"),EVENT_ID_SYMBIL_DOWNLOADER,84},
	{WSTR("Quick Driver Loader"),EVENT_ID_DRV_LOADER,16*15},
	//{WSTR("PE Unselfpacker"),EVENT_ID_VEUNPACK,86},
	WISP_MENU_RES_END
};

WISP_MENU_RES_ITEM MainMenu[]=
{
	{WSTR("Loader"),0,99,WISP_MIS_POPUP,LoaderMenu},
	{WSTR("Debugger"),0,62,WISP_MIS_POPUP,KernelDebuggerMenu},
	{WSTR("View"),0,19,WISP_MIS_POPUP,ViewMenu},
	{WSTR("Tools"),0,118,WISP_MIS_POPUP,ToolsMenu},
	{WSTR("Help"),0,30,WISP_MIS_POPUP,HelpMenu},
	{WSTR("BuyNow"),EVENT_ID_BUYNOW,74},
	WISP_MENU_RES_END
};

WISP_MENU_RES_ITEM ProcessPriorityMenu[]=
{
	{WSTR("Real time"),		EVENT_ID_REAL_TIME,		-1,WISP_MIS_CHECKBOX},
	{WSTR("High"),			EVENT_ID_HIGH,			-1,WISP_MIS_CHECKBOX},
	{WSTR("Above normal"),	EVENT_ID_ABOVE_NORMAL,	-1,WISP_MIS_CHECKBOX},
	{WSTR("Normal"),		EVENT_ID_NORMAL,		-1,WISP_MIS_CHECKBOX},
	{WSTR("Below normal"),	EVENT_ID_BELOW_NORMAL,	-1,WISP_MIS_CHECKBOX},
	{WSTR("Idle"),			EVENT_ID_IDLE,			-1,WISP_MIS_CHECKBOX},
	WISP_MENU_RES_END
};

WISP_MENU_RES_ITEM ProcessPopupMenu[]=
{
	{WSTR("Terminate"),EVENT_ID_TERMINATE,23},
	{WSTR("Set Priority Class"),EVENT_ID_SET_PRIORITY_CLASS,54,WISP_MIS_POPUP,ProcessPriorityMenu},
	{WSTR("Release Loose Memory Pages"),EVENT_ID_EMPTY_WORKING_SET,86},
	{WSTR("Detail"),EVENT_ID_DETAIL,89},
	WISP_MENU_RES_END
};

