#ifndef _SYSER_RESOURCE_H_
#define _SYSER_RESOURCE_H_

enum
{
	EVENT_ID_LOAD_MODULE = WISP_ID_USER_START,
	EVENT_ID_LOAD_SYMBOL_SYSERAPP,
	EVENT_ID_LOAD_IDA_MAP,
	EVENT_ID_LOAD_EXPORT_SYMBOLS,
	EVENT_ID_TRANSLATE_SYMBOL,
	EVENT_ID_SAVE_SYMBOLS,
	EVENT_ID_SAVE_COMMENTS,
	EVENT_ID_SAVE_HISTROYS,
	EVENT_ID_SAVE_SYSER_HISTROYS,
	EVENT_ID_START_SYSER,
	EVENT_ID_STOP_SYSER,
	EVENT_ID_CHECKNEWVERSION,
	EVENT_ID_ORDER_SYSER,
	EVENT_ID_REGISTER,
	EVENT_ID_COMMAND_REFERENCE,
	EVENT_ID_DEBUG_HELP,
	EVENT_ID_ABOUT_SYSERAPP,
	EVENT_ID_OPTION,
	EVENT_ID_BOOT_OPTION,
	EVENT_ID_VIDEO_DETECT_MODE,
	EVENT_ID_SYMBIL_DOWNLOADER,
	EVENT_ID_DRV_LOADER,
	EVENT_ID_BUYNOW,
	EVENT_ID_VEUNPACK,
	EVENT_ID_OBJECTVIEWER,
	EVENT_ID_DEBUG_MESSAGE,
	EVENT_ID_DEBUG_MESSAGE_FILTER,
	EVENT_ID_DEBUG_MESSAGE_CLEAR,
	EVENT_ID_SEND_CLIPBOARD,
	EVENT_ID_RECV_CLIPBOARD,
	EVENT_ID_EXIT,
	EVENT_ID_RECENT_FILE_SYSERAPP,
	EVENT_ID_RECENT_FILE_SYSERAPP_END = 	EVENT_ID_RECENT_FILE_SYSERAPP+8,
	EVENT_ID_TERMINATE,
	EVENT_ID_SET_PRIORITY_CLASS,
	EVENT_ID_REAL_TIME,
	EVENT_ID_HIGH,
	EVENT_ID_ABOVE_NORMAL,
	EVENT_ID_NORMAL,
	EVENT_ID_BELOW_NORMAL,
	EVENT_ID_IDLE,
	EVENT_ID_DETAIL,
	EVENT_ID_EMPTY_WORKING_SET,
	EVENT_ID_UPDATE_DRIVER_STATE,
};


extern WISP_TOOLBAR_RES_ITEM MainToolbar[];
extern WISP_MENU_RES_ITEM MainMenu[];
extern WISP_MENU_RES_ITEM ProcessPopupMenu[];





#endif

