#include "stdafx.h"
#include "BpintCmd.h"
// __declspec(naked) void BpintEntryPointer()
// {
// 	__asm{
// 
// 		//////////       0       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		//////////       1       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		//////////       2       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		//////////       3       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		//////////       4       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		//////////       5       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		//////////       6       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		//////////       7       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 
// 		//////////       8       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 
// 		//////////       9       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 
// 		//////////       a       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 
// 		//////////       b       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 
// 		//////////       c       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 
// 		//////////       d       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 
// 		//////////       e       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 
// 		//////////       f       ///////////
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)		
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 
// 		_emit(0x6a)
// 		_emit(0x00)
// 		_emit(0xe9)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 		_emit(0)
// 	}
// }
// void BpintBreakEntry()
// {
// 
// }

void InitBpintCmdEntryPointer()
{
	SyserClrCR0WP();
	DWORD EntryPointer = (DWORD)SyserBpintEntryPointer;
	DWORD dwPointer=(DWORD)SyserBpintBreakEntry;
	for(int i = 0; i < 0x100; i++,EntryPointer=EntryPointer+7)
	{
		*(BYTE*)(1+EntryPointer)=(BYTE)i;
		*(DWORD *)(3+EntryPointer)=dwPointer - EntryPointer - 7;
	}
	SyserRestoreCR0();
}

